# -*- coding: utf-8 -*-
"""poi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCsovm6oDcQOvgu_5aK8JTmnpaPN9wii
"""

pip install pandas geopandas pyrosm shapely

!apt-get install osmium-tool

!osmium tags-filter sri-lanka-260515.osm.pbf \
nwr/amenity=school,university,college,hospital,clinic,bus_station,marketplace,place_of_worship \
nwr/highway=bus_stop \
nwr/railway=station,halt \
nwr/tourism=attraction,museum,hotel,guest_house \
nwr/building=apartments \
nwr/landuse=industrial \
-o filtered_pois.osm.pbf --overwrite

import pandas as pd
import geopandas as gpd
from pyrosm import OSM
from scipy.spatial import cKDTree
import numpy as np
import gc

def fast_kdtree_poi_counts(pbf_file_path, csv_file_path, output_csv_path):
    print("1. Extracting POIs from OSM file...")
    # Read the file
    osm = OSM(pbf_file_path)

    # Our specific demand drivers
    custom_filter = {
        'amenity': ['school', 'university', 'college', 'hospital', 'clinic', 'bus_station', 'marketplace', 'place_of_worship'],
        'highway': ['bus_stop'],
        'railway': ['station', 'halt'],
        'tourism': ['attraction', 'museum', 'hotel', 'guest_house'],
        'building': ['apartments'],
        'landuse': ['industrial']
    }

    # Extract POIs
    pois = osm.get_data_by_custom_criteria(custom_filter=custom_filter,
                                           filter_type="keep",
                                           keep_nodes=True,
                                           keep_ways=True,
                                           keep_relations=False)

    print("2. Converting POIs to pure metric coordinates...")
    pois = pois[['geometry']].copy().dropna(subset=['geometry'])

    # Reproject POIs to a projected CRS before calculating centroids for accuracy
    pois_projected = pois.to_crs("EPSG:32644")
    pois_projected['geometry'] = pois_projected['geometry'].centroid

    # Use the projected and centroided GeoDataFrame for the KD-Tree
    pois_gdf = pois_projected

    # Extract raw X and Y coordinates into a highly compressed Numpy array
    poi_coords = np.array(list(zip(pois_gdf.geometry.x, pois_gdf.geometry.y)))

    # --- MASSIVE RAM SAVING STEP ---
    # Completely destroy the Pyrosm and Geopandas POI objects to free up RAM
    del osm
    del pois
    del pois_projected
    del pois_gdf
    gc.collect()

    print("3. Building Mathematical KD-Tree (Uses almost 0 RAM)...")
    # This tree allows lightning-fast radius queries
    tree = cKDTree(poi_coords)

    print("4. Loading and converting your Outlets...")
    outlets_df_initial = pd.read_csv(csv_file_path)

    # --- FIX: Robustly drop rows with NaN, non-numeric, or infinite values in Longitude or Latitude ---
    initial_rows = len(outlets_df_initial)
    # Convert to numeric, coercing errors will turn invalid parsing into NaN
    outlets_df_initial['Longitude'] = pd.to_numeric(outlets_df_initial['Longitude'], errors='coerce')
    outlets_df_initial['Latitude'] = pd.to_numeric(outlets_df_initial['Latitude'], errors='coerce')

    # Drop rows with NaN (which now includes original NaN and coerced non-numeric values)
    outlets_df_initial.dropna(subset=['Longitude', 'Latitude'], inplace=True)

    # Filter out infinite values from the numeric columns (important for cKDTree)
    outlets_df_initial = outlets_df_initial[np.isfinite(outlets_df_initial['Longitude']) & np.isfinite(outlets_df_initial['Latitude'])]

    if len(outlets_df_initial) < initial_rows:
        print(f"Warning: Dropped {initial_rows - len(outlets_df_initial)} rows from outlet_coordinates.csv due to missing, non-numeric, or infinite Longitude/Latitude values during initial cleaning.")

    # Create GeoDataFrame from the initially cleaned DataFrame
    outlets_gdf = gpd.GeoDataFrame(
        outlets_df_initial,
        geometry=gpd.points_from_xy(outlets_df_initial['Longitude'], outlets_df_initial['Latitude']),
        crs="EPSG:4326"
    )

    # Further filter out any invalid or empty geometries that might have been created
    initial_gdf_rows = len(outlets_gdf)
    outlets_gdf = outlets_gdf[outlets_gdf.geometry.is_valid & ~outlets_gdf.geometry.is_empty].copy()
    if len(outlets_gdf) < initial_gdf_rows:
        print(f"Warning: Dropped {initial_gdf_rows - len(outlets_gdf)} rows from outlets_gdf due to invalid or empty geometries.")

    outlets_gdf = outlets_gdf.to_crs("EPSG:32644")

    # Extract outlet coordinates into a Numpy array
    # Perform a final check for finitenes of coordinates from the geometry objects
    outlet_x = outlets_gdf.geometry.x
    outlet_y = outlets_gdf.geometry.y

    finite_outlet_mask = np.isfinite(outlet_x) & np.isfinite(outlet_y)
    if not finite_outlet_mask.all():
        num_non_finite_geom = (~finite_outlet_mask).sum()
        print(f"Warning: Dropped {num_non_finite_geom} outlet points due to non-finite coordinates after geometry conversion. This indicates an issue with coordinate generation.")
        outlets_gdf = outlets_gdf[finite_outlet_mask].copy()
        outlet_x = outlets_gdf.geometry.x
        outlet_y = outlets_gdf.geometry.y

    outlet_coords = np.array(list(zip(outlet_x, outlet_y)))

    # --- NEW FIX: Create a final DataFrame from outlets_gdf to ensure row count matches ---
    outlets_df_final = pd.DataFrame(outlets_gdf.drop(columns='geometry'))

    print("5. Calculating 500m and 1km distances instantly...")
    # query_ball_point returns the exact indices of POIs that fall within the radius
    # We just ask for the length (len) of that list to get our count!

    # Ensure there are still outlets to process after all filtering
    if len(outlet_coords) == 0:
        print("No valid outlet coordinates remaining after filtering. Skipping distance calculation.")
        outlets_df_final['POI_Count_500m'] = 0
        outlets_df_final['POI_Count_1km'] = 0
    else:
        counts_500m = [len(indices) for indices in tree.query_ball_point(outlet_coords, r=500)]
        counts_1km = [len(indices) for indices in tree.query_ball_point(outlet_coords, r=1000)]

        # Assign the counts to the outlets_df_final which now matches the length of counts
        outlets_df_final['POI_Count_500m'] = counts_500m
        outlets_df_final['POI_Count_1km'] = counts_1km

    print("6. Saving final results...")
    # Save to CSV
    outlets_df_final.to_csv(output_csv_path, index=False)

    print(f"Success! Data saved to {output_csv_path}")
    return outlets_df_final

# --- RUN THE SCRIPT ---
# Notice that the pbf_file_path is now the filtered file we just created!
final_data = fast_kdtree_poi_counts(
    pbf_file_path='filtered_pois.osm.pbf',
    csv_file_path='outlet_coordinates.csv',
    output_csv_path='outlets_with_poi_counts.csv'
)

# Preview the results
print(final_data.head())